<?php

use Illuminate\Database\Seeder;

class StocksSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('stocks')->insert([
            [
                'inventory_id' => '1',
                'expired_at' => '2023-01-31',
                'income_count' => '1',
                'limited_at' => '2022-12-17',
                'stock' => '1',
                'taste_name' => 'グレープ',
            ],
            [
                'inventory_id' => '2',
                'expired_at' => '2023-02-28',
                'income_count' => '2',
                'limited_at' => '2023-01-14',
                'stock' => '4',
                'taste_name' => 'グレープ',
            ],
            [
                'inventory_id' => '3',
                'expired_at' => '2023-03-31',
                'income_count' => '3',
                'limited_at' => '2023-02-14',
                'stock' => '9',
                'taste_name' => 'オレンジ',
            ],
            [
                'inventory_id' => '4',
                'expired_at' => '2023-04-30',
                'income_count' => '4',
                'limited_at' => '2023-03-16',
                'stock' => '16',
                'taste_name' => 'オレンジ',
            ],
            [
                'inventory_id' => '5',
                'expired_at' => '2023-05-31',
                'income_count' => '5',
                'limited_at' => '2023-04-16',
                'stock' => '25',
                'taste_name' => 'メロン',
            ],
            [
                'inventory_id' => '6',
                'expired_at' => '2023-06-30',
                'income_count' => '6',
                'limited_at' => '2023-05-16',
                'stock' => '36',
                'taste_name' => 'メロン',
            ],
            [
                'inventory_id' => '7',
                'expired_at' => '2023-07-31',
                'income_count' => '7',
                'limited_at' => '2023-06-16',
                'stock' => '49',
                'taste_name' => 'アップル',
            ],
            [
                'inventory_id' => '8',
                'expired_at' => '2023-08-31',
                'income_count' => '8',
                'limited_at' => '2023-07-17',
                'stock' => '64',
                'taste_name' => 'アップル',
            ],
            [
                'inventory_id' => '9',
                'expired_at' => '2023-09-30',
                'income_count' => '9',
                'limited_at' => '2023-08-16',
                'stock' => '81',
                'taste_name' => 'ストロベリー',
            ],
            [
                'inventory_id' => '10',
                'expired_at' => '2023-09-30',
                'income_count' => '10',
                'limited_at' => '2023-08-16',
                'stock' => '100',
                'taste_name' => 'ストロベリー',
            ],
            [
                'inventory_id' => '11',
                'expired_at' => '2023-09-30',
                'income_count' => '11',
                'limited_at' => '2023-08-16',
                'stock' => '121',
                'taste_name' => 'グレープ',
            ],
            [
                'inventory_id' => '12',
                'expired_at' => '2023-09-30',
                'income_count' => '12',
                'limited_at' => '2023-08-16',
                'stock' => '144',
                'taste_name' => 'グレープ',
            ],
            [
                'inventory_id' => '13',
                'expired_at' => '2023-01-31',
                'income_count' => '13',
                'limited_at' => '2022-12-17',
                'stock' => '13',
                'taste_name' => 'オレンジ',
            ],
            [
                'inventory_id' => '14',
                'expired_at' => '2023-02-28',
                'income_count' => '14',
                'limited_at' => '2023-01-14',
                'stock' => '28',
                'taste_name' => 'オレンジ',
            ],
            [
                'inventory_id' => '15',
                'expired_at' => '2023-03-31',
                'income_count' => '15',
                'limited_at' => '2023-02-14',
                'stock' => '45',
                'taste_name' => 'メロン',
            ],
            [
                'inventory_id' => '16',
                'expired_at' => '2023-04-30',
                'income_count' => '16',
                'limited_at' => '2023-03-16',
                'stock' => '64',
                'taste_name' => 'メロン',
            ],
            [
                'inventory_id' => '17',
                'expired_at' => '2023-05-31',
                'income_count' => '17',
                'limited_at' => '2023-04-16',
                'stock' => '85',
                'taste_name' => 'アップル',
            ],
            [
                'inventory_id' => '18',
                'expired_at' => '2023-06-30',
                'income_count' => '18',
                'limited_at' => '2023-05-16',
                'stock' => '108',
                'taste_name' => 'アップル',
            ],
            [
                'inventory_id' => '19',
                'expired_at' => '2023-07-31',
                'income_count' => '19',
                'limited_at' => '2023-06-16',
                'stock' => '133',
                'taste_name' => 'ストロベリー',
            ],
            [
                'inventory_id' => '20',
                'expired_at' => '2023-08-31',
                'income_count' => '20',
                'limited_at' => '2023-07-17',
                'stock' => '160',
                'taste_name' => 'ストロベリー',
            ],
            [
                'inventory_id' => '1',
                'expired_at' => '2023-09-30',
                'income_count' => '21',
                'limited_at' => '2023-08-16',
                'stock' => '9',
                'taste_name' => 'グレープ',
            ],
            [
                'inventory_id' => '2',
                'expired_at' => '2023-09-30',
                'income_count' => '22',
                'limited_at' => '2023-08-16',
                'stock' => '20',
                'taste_name' => 'グレープ',
            ],
            [
                'inventory_id' => '3',
                'expired_at' => '2023-09-30',
                'income_count' => '23',
                'limited_at' => '2023-08-16',
                'stock' => '33',
                'taste_name' => 'オレンジ',
            ],
            [
                'inventory_id' => '4',
                'expired_at' => '2023-09-30',
                'income_count' => '24',
                'limited_at' => '2023-08-16',
                'stock' => '48',
                'taste_name' => 'オレンジ',
            ],
            [
                'inventory_id' => '5',
                'expired_at' => '2023-01-31',
                'income_count' => '25',
                'limited_at' => '2022-12-17',
                'stock' => '5',
                'taste_name' => 'メロン',
            ],
            [
                'inventory_id' => '6',
                'expired_at' => '2023-02-28',
                'income_count' => '26',
                'limited_at' => '2023-01-14',
                'stock' => '12',
                'taste_name' => 'メロン',
            ],
            [
                'inventory_id' => '7',
                'expired_at' => '2023-03-31',
                'income_count' => '27',
                'limited_at' => '2023-02-14',
                'stock' => '21',
                'taste_name' => 'アップル',
            ],
            [
                'inventory_id' => '8',
                'expired_at' => '2023-04-30',
                'income_count' => '28',
                'limited_at' => '2023-03-16',
                'stock' => '32',
                'taste_name' => 'アップル',
            ],
            [
                'inventory_id' => '9',
                'expired_at' => '2023-05-31',
                'income_count' => '29',
                'limited_at' => '2023-04-16',
                'stock' => '45',
                'taste_name' => 'ストロベリー',
            ],
            [
                'inventory_id' => '10',
                'expired_at' => '2023-06-30',
                'income_count' => '30',
                'limited_at' => '2023-05-16',
                'stock' => '60',
                'taste_name' => 'ストロベリー',
            ],
            [
                'inventory_id' => '11',
                'expired_at' => '2023-07-31',
                'income_count' => '31',
                'limited_at' => '2023-06-16',
                'stock' => '77',
                'taste_name' => 'グレープ',
            ],
            [
                'inventory_id' => '12',
                'expired_at' => '2023-08-31',
                'income_count' => '32',
                'limited_at' => '2023-07-17',
                'stock' => '96',
                'taste_name' => 'グレープ',
            ],
            [
                'inventory_id' => '13',
                'expired_at' => '2023-09-30',
                'income_count' => '33',
                'limited_at' => '2023-08-16',
                'stock' => '117',
                'taste_name' => 'オレンジ',
            ],
            [
                'inventory_id' => '14',
                'expired_at' => '2023-09-30',
                'income_count' => '34',
                'limited_at' => '2023-08-16',
                'stock' => '140',
                'taste_name' => 'オレンジ',
            ],
            [
                'inventory_id' => '15',
                'expired_at' => '2023-09-30',
                'income_count' => '35',
                'limited_at' => '2023-08-16',
                'stock' => '165',
                'taste_name' => 'メロン',
            ],
            [
                'inventory_id' => '16',
                'expired_at' => '2023-09-30',
                'income_count' => '36',
                'limited_at' => '2023-08-16',
                'stock' => '192',
                'taste_name' => 'メロン',
            ],
            [
                'inventory_id' => '17',
                'expired_at' => '2023-01-31',
                'income_count' => '37',
                'limited_at' => '2022-12-17',
                'stock' => '17',
                'taste_name' => 'アップル',
            ],
            [
                'inventory_id' => '18',
                'expired_at' => '2023-02-28',
                'income_count' => '38',
                'limited_at' => '2023-01-14',
                'stock' => '36',
                'taste_name' => 'アップル',
            ],
            [
                'inventory_id' => '19',
                'expired_at' => '2023-03-31',
                'income_count' => '39',
                'limited_at' => '2023-02-14',
                'stock' => '57',
                'taste_name' => 'ストロベリー',
            ],
            [
                'inventory_id' => '20',
                'expired_at' => '2023-04-30',
                'income_count' => '40',
                'limited_at' => '2023-03-16',
                'stock' => '80',
                'taste_name' => 'ストロベリー',
            ],
            [
                'inventory_id' => '1',
                'expired_at' => '2023-05-31',
                'income_count' => '41',
                'limited_at' => '2023-04-16',
                'stock' => '5',
                'taste_name' => 'グレープ',
            ],
            [
                'inventory_id' => '2',
                'expired_at' => '2023-06-30',
                'income_count' => '42',
                'limited_at' => '2023-05-16',
                'stock' => '12',
                'taste_name' => 'グレープ',
            ],
            [
                'inventory_id' => '3',
                'expired_at' => '2023-07-31',
                'income_count' => '43',
                'limited_at' => '2023-06-16',
                'stock' => '21',
                'taste_name' => 'オレンジ',
            ],
            [
                'inventory_id' => '4',
                'expired_at' => '2023-08-31',
                'income_count' => '44',
                'limited_at' => '2023-07-17',
                'stock' => '32',
                'taste_name' => 'オレンジ',
            ],
            [
                'inventory_id' => '5',
                'expired_at' => '2023-09-30',
                'income_count' => '45',
                'limited_at' => '2023-08-16',
                'stock' => '45',
                'taste_name' => 'メロン',
            ],
            [
                'inventory_id' => '6',
                'expired_at' => '2023-09-30',
                'income_count' => '46',
                'limited_at' => '2023-08-16',
                'stock' => '60',
                'taste_name' => 'メロン',
            ],
            [
                'inventory_id' => '7',
                'expired_at' => '2023-09-30',
                'income_count' => '47',
                'limited_at' => '2023-08-16',
                'stock' => '77',
                'taste_name' => 'アップル',
            ],
            [
                'inventory_id' => '8',
                'expired_at' => '2023-09-30',
                'income_count' => '48',
                'limited_at' => '2023-08-16',
                'stock' => '96',
                'taste_name' => 'アップル',
            ],
            [
                'inventory_id' => '9',
                'expired_at' => '2023-01-31',
                'income_count' => '49',
                'limited_at' => '2022-12-17',
                'stock' => '9',
                'taste_name' => 'ストロベリー',
            ],
            [
                'inventory_id' => '10',
                'expired_at' => '2023-02-28',
                'income_count' => '50',
                'limited_at' => '2023-01-14',
                'stock' => '20',
                'taste_name' => 'ストロベリー',
            ],
            [
                'inventory_id' => '11',
                'expired_at' => '2023-03-31',
                'income_count' => '51',
                'limited_at' => '2023-02-14',
                'stock' => '33',
                'taste_name' => 'グレープ',
            ],
            [
                'inventory_id' => '12',
                'expired_at' => '2023-04-30',
                'income_count' => '52',
                'limited_at' => '2023-03-16',
                'stock' => '48',
                'taste_name' => 'グレープ',
            ],
            [
                'inventory_id' => '13',
                'expired_at' => '2023-05-31',
                'income_count' => '53',
                'limited_at' => '2023-04-16',
                'stock' => '65',
                'taste_name' => 'オレンジ',
            ],
            [
                'inventory_id' => '14',
                'expired_at' => '2023-06-30',
                'income_count' => '54',
                'limited_at' => '2023-05-16',
                'stock' => '84',
                'taste_name' => 'オレンジ',
            ],
            [
                'inventory_id' => '15',
                'expired_at' => '2023-07-31',
                'income_count' => '55',
                'limited_at' => '2023-06-16',
                'stock' => '105',
                'taste_name' => 'メロン',
            ],
            [
                'inventory_id' => '16',
                'expired_at' => '2023-08-31',
                'income_count' => '56',
                'limited_at' => '2023-07-17',
                'stock' => '128',
                'taste_name' => 'メロン',
            ],
            [
                'inventory_id' => '17',
                'expired_at' => '2023-09-30',
                'income_count' => '57',
                'limited_at' => '2023-08-16',
                'stock' => '153',
                'taste_name' => 'アップル',
            ],
            [
                'inventory_id' => '18',
                'expired_at' => '2023-09-30',
                'income_count' => '58',
                'limited_at' => '2023-08-16',
                'stock' => '180',
                'taste_name' => 'アップル',
            ],
            [
                'inventory_id' => '19',
                'expired_at' => '2023-09-30',
                'income_count' => '59',
                'limited_at' => '2023-08-16',
                'stock' => '209',
                'taste_name' => 'ストロベリー',
            ],
            [
                'inventory_id' => '20',
                'expired_at' => '2023-09-30',
                'income_count' => '60',
                'limited_at' => '2023-08-16',
                'stock' => '240',
                'taste_name' => 'ストロベリー',
            ],
        ]);
    }
}
